#!/bin/bash

set -e

cd "$(dirname "$0")/.."

COMMIT=$(git rev-parse HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

docker build \
  -t "registry.zielmaker.nl/dvd-screensaver-website:$COMMIT" \
  -t "registry.zielmaker.nl/dvd-screensaver-website:$BRANCH" \
  .

docker push "registry.zielmaker.nl/dvd-screensaver-website:$COMMIT"
docker push "registry.zielmaker.nl/dvd-screensaver-website:$BRANCH"
